import type { Metadata } from "next";
import { Geist, Geist_Mono, Merriweather } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const merriweather = Merriweather({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "My Next App",
  description: "Generated by Next Level Team",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        // className={geistMono.className}
        // className={geistSans.className}
        className={merriweather.className}
      >
        <main className="min-h-dvh">
          {children}
        </main>
        <footer className="text-center text-4xl my-5">
          This is Footer
        </footer>
      </body>
    </html>
  );
}
